### ISSUE TITLE
 'Namespace' object has no attribute 'attack'

### ISSUE THREAD

**Issue by StephenYF** [AaronSun2000/MakeupAttack#5]
Traceback (most recent call last):
  File "train_model.py", line 246, in <module>
    main()
  File "train_model.py", line 204, in main
    poison(args)
  File "train_model.py", line 149, in poison
    save_path = f'ckpt/{args.dataset}_{args.network}_{args.attack}.pt'
AttributeError: 'Namespace' object has no attribute 'attack'
can you help me ?THS!

**Comment by AaronSun2000** [comment]
Hello, thank you for your attention.

Based on your question, we have identified a few minor issues with the code and have re-uploaded the updated training code. If you have any further questions, please feel free to contact me at any time~
